version: '3'

vars:
  IMAGE: '{{.IMAGE | default "vllm-chill"}}'
  TAG: '{{.TAG | default "latest"}}'

tasks:
  # Task 1: Development
  dev:
    desc: "Run tests and build locally"
    cmds:
      - go mod download
      - go test -v ./...
      - go build -o bin/vllm-chill ./cmd/autoscaler
      - echo "Build successful! Binary at bin/vllm-chill"

  # Task 2: Test
  test:
    desc: "Run all tests with coverage"
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  # Task 3: Build & Push Docker image
  docker:
    desc: "Build and push multi-arch Docker image"
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t {{.IMAGE}}:{{.TAG}} --push .
      - echo "image pushed: {{.IMAGE}}:{{.TAG}}"

  # Task 4: Local run
  run:
    desc: "Run locally (requires kubeconfig)"
    cmds:
      - go run ./cmd/autoscaler serve
