version: '3'

vars:
  IMAGE: '{{.IMAGE | default "efortin/vllm-chill"}}'
  TAG: '{{.TAG | default "latest"}}'

tasks:
  # Task 1: Development
  dev:
    desc: "Run tests and build locally"
    cmds:
      - go mod download
      - go test -v ./...
      - go build -o bin/vllm-chill ./cmd/autoscaler
      - echo "Build successful! Binary at bin/vllm-chill"

  # Task 2: Test
  test:
    desc: "Run all tests with coverage"
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  # Task 3: Lint
  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...

  # Task 4: Lint with auto-fix
  "lint:fix":
    desc: "Run golangci-lint with auto-fix"
    cmds:
      - golangci-lint run --fix ./...

  # Task 5: Build & Push Docker image
  docker:
    desc: "Build and push multi-arch Docker image"
    cmds:
      - "docker buildx build --platform linux/amd64,linux/arm64 -t {{.IMAGE}}:{{.TAG}} --push ."
      - 'echo "image pushed: {{.IMAGE}}:{{.TAG}}"'

  # Task 5a: Build & Push Docker :dev image
  "docker:dev":
    desc: "Build and push Docker image with :dev tag"
    cmds:
      - "docker buildx build --platform linux/amd64 -t {{.IMAGE}}:dev --push ."
      - 'echo "image pushed: {{.IMAGE}}:dev"'

  # Task 6: Build
  build:
    desc: "Build binary"
    cmds:
      - go build -o bin/vllm-chill ./cmd/autoscaler
      - echo "Build successful! Binary at bin/vllm-chill"

  # Task 7: Local run
  run:
    desc: "Run locally (requires kubeconfig)"
    cmds:
      - go run ./cmd/autoscaler serve

  # Task 8: Full check (lint + test + build)
  check:
    desc: "Run full checks (lint, test, build)"
    cmds:
      - task: lint
      - task: test
      - task: build
      - echo "All checks passed!"
