version: '3'

includes:
  dev:
    taskfile: ./Taskfile.dev.yml
    dir: .
  k3d:
    taskfile: ./Taskfile.k3d.yml
    dir: .

vars:
  IMAGE: '{{.IMAGE | default "efortin/vllm-chill"}}'
  TAG: '{{.TAG | default "latest"}}'
  CLUSTER_NAME: vllm-test
  K8S_CONTEXT: k3d-vllm-test
  NAMESPACE: vllm

tasks:
  # Main development workflow
  default:
    desc: "Run default development workflow (test + build)"
    cmds:
      - task: dev:test
      - task: dev:build

  # Run all tests (unit + integration)
  "test:all":
    desc: "Run all tests (unit + integration)"
    cmds:
      - task: dev:test
      - task: k3d:test:go
      - echo "All tests passed!"

  # Full CI check (lint + test + build)
  ci:
    desc: "Run full CI checks (lint + test + build)"
    cmds:
      - task: dev:check

  # Release workflow (check + docker build)
  release:
    desc: "Run release workflow (check + docker build)"
    cmds:
      - task: dev:check
      - task: dev:docker:build
      - echo "Release complete!"
