---
# ConfigMap for vLLM model configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-config
  namespace: vllm
data:
  # Model identification
  MODEL_NAME: "Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8"
  SERVED_MODEL_NAME: "qwen3-coder-30b-fp8"

  # Parsing configuration
  TOOL_CALL_PARSER: "qwen3_coder"
  REASONING_PARSER: ""

  # vLLM runtime parameters
  TENSOR_PARALLEL_SIZE: "2"
  MAX_MODEL_LEN: "65536"
  GPU_MEMORY_UTILIZATION: "0.91"
  ENABLE_CHUNKED_PREFILL: "true"
  MAX_NUM_BATCHED_TOKENS: "4096"
  MAX_NUM_SEQS: "16"
  DTYPE: "float16"
  DISABLE_CUSTOM_ALL_REDUCE: "true"
  ENABLE_PREFIX_CACHING: "true"
  CPU_OFFLOAD_GB: "0"
  ENABLE_AUTO_TOOL_CHOICE: "true"

---
# ServiceAccount for vllm-chill proxy
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-chill
  namespace: vllm

---
# Role for vllm-chill to manage vLLM deployment and ConfigMap (namespace-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-chill
  namespace: vllm
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]

---
# RoleBinding for vllm-chill
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-chill
  namespace: vllm
subjects:
- kind: ServiceAccount
  name: vllm-chill
  namespace: vllm
roleRef:
  kind: Role
  name: vllm-chill
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for vllm-chill to read VLLMModels (cluster-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vllm-chill-models
rules:
- apiGroups: ["vllm.sir-alfred.io"]
  resources: ["models"]
  verbs: ["get", "list"]

---
# ClusterRoleBinding for vllm-chill to read VLLMModels
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vllm-chill-models
subjects:
- kind: ServiceAccount
  name: vllm-chill
  namespace: vllm
roleRef:
  kind: ClusterRole
  name: vllm-chill-models
  apiGroup: rbac.authorization.k8s.io
---
# Ingress (optional - adjust based on your ingress controller)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vllm-chill
  namespace: vllm
  annotations:
    # Example for nginx ingress
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: vllm.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vllm-chill-svc
            port:
              number: 80
