//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMModel) DeepCopyInto(out *VLLMModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMModel.
func (in *VLLMModel) DeepCopy() *VLLMModel {
	if in == nil {
		return nil
	}
	out := new(VLLMModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLLMModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMModelList) DeepCopyInto(out *VLLMModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLLMModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMModelList.
func (in *VLLMModelList) DeepCopy() *VLLMModelList {
	if in == nil {
		return nil
	}
	out := new(VLLMModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLLMModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMModelSpec) DeepCopyInto(out *VLLMModelSpec) {
	*out = *in
	if in.EnableChunkedPrefill != nil {
		in, out := &in.EnableChunkedPrefill, &out.EnableChunkedPrefill
		*out = new(bool)
		**out = **in
	}
	if in.DisableCustomAllReduce != nil {
		in, out := &in.DisableCustomAllReduce, &out.DisableCustomAllReduce
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrefixCaching != nil {
		in, out := &in.EnablePrefixCaching, &out.EnablePrefixCaching
		*out = new(bool)
		**out = **in
	}
	if in.EnableAutoToolChoice != nil {
		in, out := &in.EnableAutoToolChoice, &out.EnableAutoToolChoice
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMModelSpec.
func (in *VLLMModelSpec) DeepCopy() *VLLMModelSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMModelStatus) DeepCopyInto(out *VLLMModelStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMModelStatus.
func (in *VLLMModelStatus) DeepCopy() *VLLMModelStatus {
	if in == nil {
		return nil
	}
	out := new(VLLMModelStatus)
	in.DeepCopyInto(out)
	return out
}
